
courses <- AsyncQuery$new(function(conn,filters) {dbGetQuery(conn, sqlInterpolate(conn, paste("SELECT DISTINCT *
                                                                                              FROM dt_courses")))}
)

courseStructure <- AsyncQuery$new(function(conn,filters) {
  # Using subquery generated by filters to simplify logic
  # dbGetQuery(conn, sqlInterpolate(
  #   conn, "SELECT * FROM dv_students INNER JOIN (?squery) AS S ON (dv_students.user_id = S.user_id)",
  #   squery = filters$student$subquery(conn)
  # ))
  dbGetQuery(conn, sqlInterpolate(conn, paste("SELECT DISTINCT *
                                                                                                FROM dt_course_str",
                                              "WHERE course_id = ?course"),
                                  course = input$crsInput
                                  
                                  
                                  
                                  
  ))})
